### ISSUE TITLE
Stop

### ISSUE THREAD

**Issue by icefootMan** [esh123cookie/RankUpV2#1]
Please Stop Threating People Like if u dont give me credit ur gonna get your server files delete. STOP. I Don't use this plugin because my server has a dev. I Already Contacted a Admin About This Plugin And Threating People Because They Dont give you credit. Hope u Have A Good Day.

**Comment by esh123cookie** [comment]
Um first it is my plugin, second I don't want fake dev's putting their name on this plugin or selling it for their own profit. The plugin will not do anything to your server unless you claim this plugin as yours.

**Comment by icefootMan** [comment]
I now its your plugin lol, i said i don't use this plugin because my server has a developer, 2 Lets Say You Have 2 Apples, Ana which is evil Comes and Takes Them ALL. Wouldn't that be sad? You could simply warn them, u don't need to destroy their server.

**Comment by esh123cookie** [comment]
I doubt a warning would do anything. That's nice your server has a dev, but I still don't want someone taking credit. It's really not difficult to just not change the author of the plugin. If a user uses it as what its meant to be then the plugin will work as its supposed to. 

If the user does want to give a plugin request I linked my discord and my discord user. If they want to work on it they can ask for permission.

**Comment by icefootMan** [comment]
Still to rude to destroy a hard man's work, when i started making my server it taked my like a month, plus your antisteal its stupid(don't wanna be rude or something) i use server pro and in the control panel, i see all the ops and i can remove/add ops, plus if u like delete thier server files they would 100% have a backup, i have a feature that makes auto daily backup, i think every paid server has this feature.

**Comment by esh123cookie** [comment]
Well look, it may be harsh, yet if you just think about it. This makes complete sense unless someone tries to complete ownership of this plugin it'll work perfectly. It's like doing something illegal and saying that person shouldn't go to jail. This is also my hard work which I am constantly working on to improve and make it better for people who want to use it. I know how it is to make a server, I've been working on mine for almost a year. That doesn't mean I have the right to take over someone elses work.

**Comment by icefootMan** [comment]
Ok yeah you are maybe right, but still your AntiSteal or whatever is called its Stupid, Everyone Has a Backup of Thier Server, and even if u dont delete the files and have op they can always go to thier control panels and see the Operators, Its Like Getting a Virus on Your PC But That Virus is so Bad Coded That u Can Kill The Process from Task Manager.

**Comment by esh123cookie** [comment]
Well ig it works sometimes if they have a backup oh well, they still wont be able to use the plugin unless they learn to devs or use it with my credit.
