### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by IceCruelStuff** [esh123cookie/RankUpV2#2]
The deleting server files thing on this plugin can be easily bypassed by deleting some parts of the code. I'm not saying that I would do it, I'm just saying it can be done easily.

**Comment by esh123cookie** [comment]
I understand that, but a lot of fake devs don't actually know what to remove causing errors in the plugins.

**Comment by IceCruelStuff** [comment]
But the people who download from fake devs didn't do anything. They did not change the author name but their server files are still going to be deleted.

**Comment by esh123cookie** [comment]
Well I can't change that really, but this prevents most fake devs

**Comment by MakerbakerYT** [comment]
Can u guys stop fighting
