### ISSUE TITLE
OH MY GOD!!

### ISSUE THREAD

**Issue by minijaham** [esh123cookie/RankUpV2#4]
ANTI STEAL CODE IS FUCKING EPIC!!
COULD I USE IT FOR MY PLUGINS??????

**Comment by esh123cookie** [comment]
> ANTI STEAL CODE IS FUCKING EPIC!!
> COULD I USE IT FOR MY PLUGINS??????

 Lool sure

**Comment by esh123cookie** [comment]
I actually really need to update this plugin, it's super outdated with how its setup and is just plain bad so i may upgrade the anti steal aswell

**Comment by minijaham** [comment]
Oh, I will be looking forward to it >:)

**Comment by esh123cookie** [comment]
If you want to dm message on my discord. Thanks

**Comment by minijaham** [comment]
ok
